[project]
name = "norse-server"
authors = [
    {name = "Jens E. Pedersen", email = "jeped@kth.se"},
    {name = "Sebastian Spreizer", email = "spreizer@web.de"},
]
description = "Server for executing arbitrary PyTorch and Norse code"
readme = "README.md"
requires-python = ">=3.8"
keywords = ["Python", "PyTorch", "Norse", "Flask"]
license = {text = "BSD-3-Clause"}
classifiers = [
    "Framework :: Flask",
    "Programming Language :: Python :: 3",
]
dependencies = [
    "requests",
    "flask",
    "flask-cors",
    "norse",
    "werkzeug",
    "RestrictedPython",
    "gunicorn"
]
dynamic = ["version"]

[tool.setuptools]
package-dir = {"norse_server" = "src"}
script-files = ["scripts/norse-server"]

[tool.setuptools.dynamic]
version = {attr = "src.__version__"}